# Generated by Django 5.0.6 on 2024-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField()),
                ("query", models.TextField()),
                ("result", models.TextField()),
            ],
        ),
    ]
