# Generated by Django 5.0.6 on 2024-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="problemstatement",
            name="level",
            field=models.CharField(
                choices=[
                    ("BEG", "Beginner"),
                    ("INT", "Intermediate"),
                    ("ADV", "Advanced"),
                ],
                default="BEG",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="problemstatement",
            name="tag",
            field=models.ManyToManyField(
                related_name="problem_statements", to="myapp.tag"
            ),
        ),
    ]
