# Generated by Django 5.0.6 on 2024-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_tag_problemstatement_level_problemstatement_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemstatement",
            name="level",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="problemstatement",
            name="result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problemstatement",
            name="tag",
            field=models.ManyToManyField(to="myapp.tag"),
        ),
    ]
